#!/bin/bash

usage()
{
    cat << EOF
usage: $0 options

Index and search files using dmenu

OPTIONS:
   -h      Show this message
   -o      Store index [default: /tmp/fmenu_index]
   -i      Search folders [default: $HOME]
   -x      Exclude files [default: ".*\/..*" (i.e. dot-files)]
   -d      dmenu parameters [default: -i -l 20]
   -f      force reloading index [default: false]
   -t      time [default: 5min]
   -u      Just update the index
   -n      Prevent it from building the index
EOF
}

FORCE=false
INDEX="/tmp/fmenu_index"
DMENU="-i -l 20"
TIME="+5"
INPUT=$HOME
EXCLUDE='.*/\..*'
DRY=false
BUILD_INDEX=true
SHIFT=0
while getopts "ht:fd:o:i:x:un" OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         f)
             FORCE=true
             SHIFT=$((SHIFT + 1))
             ;;
         d)
             DMENU=$OPTARG
             SHIFT=$((SHIFT + 2))
             ;;
         t)
             TIME=$OPTARG
             SHIFT=$((SHIFT + 2))
             ;;
         o)
             INDEX=$OPTARG
             SHIFT=$((SHIFT + 2))
             ;;
         i)
             INPUT=$OPTARG
             SHIFT=$((SHIFT + 2))
             ;;
         x)
             EXCLUDE=$OPTARG
             SHIFT=$((SHIFT + 2))
             ;;
         u)
             FORCE=true
             DRY=true
             SHIFT=$((SHIFT + 1))
             ;;
         n)
             BUILD_INDEX=false
             SHIFT=$((SHIFT + 1))
             ;;
         ?)
             usage
             exit
             ;;
     esac
done

shift $SHIFT

function index_files {
    find "$INPUT" \( ! -regex "$EXCLUDE" \) | sed 's/ /\\ /g' | sort -f > "$INDEX.raw"
    iconv -f utf-8 -t utf-8 -c "$INDEX.raw" -o "$INDEX"
    rm "$INDEX.raw"
}

if ( $BUILD_INDEX )
then
    if [[ ! -a "$INDEX" ]] ||  ( test `find $INDEX -mmin $TIME` ) || ($FORCE)
    then
        index_files
    fi
fi

if ( ! $DRY )
then
    if [ -z $@ ]
    then
        if [[ -a "$INDEX" ]]
        then
            cat "$INDEX"
        fi
    else
        xdg-open $@ > /dev/null &
    fi
fi
